---
# These tasks are responsible for copying the latest dev/production code from
# the version control system.

- name: empty uploads folder
  file: path=/var/www/html state=absent recurse=yes

- name: ownership on uploads folder (user)
  file: path=/var/www/html owner=vagrant group=vagrant mode=0755 state=directory

- name: copy the code from repository
  sudo: no
  git: repo={{ repository }} dest=/var/www/html accept_hostkey=true

- name: ownership on uploads folder (root)
  sudo: yes
  file: path=/var/www/html owner=root group=root state=directory recurse=yes

- name: create uploads folder
  file: path=/var/www/html/uploads owner=apache group=apache state=directory

- name: create storage folder
  file: path=/var/www/storage owner=apache group=apache state=directory

- name: create ffmpeg storage link
  file: src=/usr/bin/ffmpeg dest=/var/www/storage/ffmpeg owner=apache group=apache state=link

- name: create ffprobe storage link
  file: src=/usr/bin/ffmpeg dest=/var/www/storage/ffmpeg owner=apache group=apache state=link

- name: create CI database.php config file
  template: src=database.php.j2 dest=/var/www/html/application/config/database.php  owner=root group=root mode=0644

- name: create CI testing config directory
  file: path=/var/www/html/application/config/testing state=directory owner=root group=root mode=0755

- name: create CI test database.php config file
  template: src=test_database.php.j2 dest=/var/www/html/application/config/testing/database.php  owner=root group=root mode=0644
